config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  root "birds#index"
  # get "/birds", to: "birds#index"

  # get "/birds/new", to: "birds#new"
  # post "/birds", to: "birds#create"

  # get "/birds/:id", to: "birds#show"
  # get "/birds/:id/edit", to: "birds#edit"
  # patch "/birds/:id", to: "birds#update"
  # put "/birds/:id", to: "birds#update"

  # delete "/birds/:id", to: "birds#destroy"
  resources :birds


  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bird.rb
class Bird < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  before_action :set_bird, only: %i[ show edit update destroy]

  def index
    @birds = Bird.all # @ = instance variable, hands it to view automatically
  end

  def show
  end

  def new
    @bird = Bird.new
  end

  def create
    @bird = Bird.new(bird_params)
    if @bird.save # validate, save if success, save returns bool, if i put bang! then it raises
      redirect_to @bird # automatically goes to "show" of that bird
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @bird.update(bird_params)
      redirect_to @bird
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bird.destroy
    redirect_to birds_path
  end
    
  private
    def set_bird
      @bird = Bird.find(params[:id])
    end

      
  # This filters the incoming param and make sure there is bird array with param name
  # other obj are ignored
    def bird_params
      params.expect(bird: [ :name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/views/birds/_form.html.erb
<!--_ shows this is a partial -> a reusable html-->

<!--Handles CSRF token-->
<!--We send the new bird model, so it knows it's POST/PUT-->
<!--no @ instance, but localvar to be defined when rendering the partial -->
<%= form_with model: bird do |form| %>
    <% if form.object.errors.any?%>
        <p class="error"><%= form.object.errors.full_message.first%>
    <% end %>
<div>
<%= form.label :name%>
<%= form.text_field :name %>
</div>
<div>
<%= form.submit%><!-- adjusts the text on button accordingly-->
</div>

<%end%>

app/views/birds/edit.html.erb
<h1>Edit bird<h1>

<%= render "form", bird: @bird%>
<%= link_to "Cancel", @bird%>

app/views/birds/index.html.erb
<h1>Birds</h1>

<%= link_to "New Bird", new_bird_path %>

<div id="birds">
  <% @birds.each do |bird| %>
    <div>
      <%= link_to bird.name, bird_path(bird.id) %>
    </div>
  <% end %>
</div>

app/views/birds/new.html.erb
<h1>New Bird</h1>

<%= render "form", bird: @bird%>
<%= link_to "Cancel", birds_path%>

app/views/birds/show.html.erb
<h1><%= @bird.name %></h1>

<%= link_to "Back", birds_path %>
<%= link_to "Edit", edit_bird_path(@bird)%>
<!--A form with a button with text delete, makes a delete req, after confirming-->
<%= button_to "Delete", @bird, method: :delete, data: { turbo_confirm: "Are you sure?" }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bird Dashboard" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Bird Dashboard">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>